<?php $this->title = "Vše o ethanolu";
$this->headTitle($this->title); ?>

<p>Bioethanol E85 je směs paliva tvořena z 85% etanolem a z 15% benzínem. Jde o takzvané biopalivo, které je obnovitelným zdrojem energie.
    Bioetanol obecně lze používat na nízkoprocentní přimíchávání do automobilových benzínů, které se řídí zákonem č. 180/2007 Sb. (vychází z evropské směrnice 2003/30/ES)
    a na vysokoprocentní bioetanolové směsi, zejména pak právě palivo E85.</p>
<br><br />

<p>V současné době jsou vysokoprocentní ethanolové směsi využívány ve vozidlech, která mohou být provozovány jak na běžný benzin, palivo E85, tak i na libovolnou směs benzinu s palivem E85.
    Palivo E85 je možné spalovat i v běžných vozidlech, ale je třeba provést jednoduchou úpravu řídicí jednotky motoru, která spočívá v prodloužení doby vstřiku paliva.</p>

<h2>Jak funguje řídící jednotka</h2>
<p>Řídící jednotka prodlužuje dobu vstřiku paliva do válce v přesně daném množství, které je nastaveno tak, aby docházelo k dokonalému spalování směsi.
    Řídící jednotky jsou plně automatizované a starající se o regulaci poměru směsi, čímž je zajištěn správný chod, při kterém můžete jezdit jak na samotný benzín, směs benzínu s ethanolem E85
    nebo jen na čistý ethanol E85.</p>

<h2>Jakým způsobem zvyšuje E85 výkon motoru</h2>
<p>
Ethanol obsahuje 30% kyslíku oproti benzínu, který ho obsahuje pouze 4%. Díky tomu dochází k efektivnějšímu hoření, což se projevuje, jak na zvýšení výkonu motoru, tak na snížení
množství emisí.
</p>

<h2>Jaký je vliv paliva E85 na motor vozidla</h2>
<p>
Vliv používání paliva E85 na motor vozidla je pozivitní, což ukazují zkušenosti v zemích (např. Švédsko), kde jezdí automobily na E85 již řadu let.
Provoz automobilu je levnější a ekologičtější. Navíc má ethanol E85 čistící vlastnosti a při jeho používání tak dochází k pročištění a dalšímu nezanášení vstřikovacích trysek.
Spalováním nevznikají karbonové usazeniny. Ethanol E85 hoří za nižších teplot než benzín a tím dochází k menšímu opotřebení pístních kroužků.
</p>

<br><br />
<h3 style="text-align: left;;">Máte otázky? Pokud jste zde nenalezli odpověď na dotaz, který by Vás zajímal
    <a class="hot_link" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'contact')); ?>"  <?php echo '>'; ?>kontaktujte nás</a> nebo telefonicky na čísle <b  style="color:#D76F37;"> +420 777 672 277</b></h3>
