<?php $this->title = "Kontakt";
$this->headTitle($this->title); ?>

<p>Na tomto místě se nás můžete pomocí formuláře na cokoliv zeptat, rádi Vám zodpovíme všechny Vaše dotazy. V případě potřeby můžete samozřejmě využít také našeho telefonického kontaktu.</p>
<br />

<div class="contact_info">
    <div class="address">
        <h3>Adresa</h3>
        <p>
            Stanislav Kratochvíl<br />
            Smetanova 1580<br />
            565 01 Choceň<br />
            Česká Republika
        </p>
        <p>IČO: 42916925 </p>
    </div>

    <div class="phone">
        <h3>Telefon</h3>
        <p>
            +420 <b>777 672 277</b><br />
        </p>
    </div>

    <div class="phone">
        <h3>E-mail</h3>
        <p>
            <a class="email" href="goodcar@centrum.cz">goodcar@centrum.cz</a>
        </p>

    </div>

    <div class="phone">
        <h3>Web</h3>
        <a class="email" href="www.goodcar.cz">www.goodcar.cz</a>
    </div>



</div>

<div class="cleaner"></div>
<div class="contact_form_velky">
    <?php echo $this->contactform2 ?>
</div>
