<?php $this->title = "PŘESTAVBY VOZIDEL NA BIOETHANOL E85";
$this->headTitle($this->title); ?>

<h2>Vítejte na stránkách společnosti <b>GoodCAR</b></h2>

<p>Zamysleli jste se někdy, jak se dopravovat Vaším automobilem levněji? Tuto otázky si položilo jistě mnoho z Vás a my, ve společnosti GoodCAR, jsme si ji položili také.
    <br><br />
    Odpověď je docela jednoduchá, stačí tankovat levnější palivo. Jde o palivo pojmenované bioethanol E85, které je certifikované a schválené pro celou EU
    a jenž Vám dnes nabídne již více jak 200 čerpacích stanic po celé České Republice, kterých stále přibývá.
    Na toto palivo již řadu let jezdí několik milionů automobilů v celé Evropě, především ve Skandinávii a Norsku. V České republice jezdí v současné době již více jak 100 000 automobilů.</p>
<br><br />

<h2>Proč právě E85</h2>
<p>Bioethanol E85 má mnoho pozitivních vlatností, které z něj činí účinnou alternativu k běžně používaným palivům. 
    Například <i style="color:#D76F37;"><b>zvyšuje výkonnost motoru</b></i> Vašeho vozu a je daleko <i style="color:#D76F37;"><b>ekologičtější</b></i> než běžná paliva. Jedním z těch nejpodstatnějších pozitiv,
    které je v dnešních dnech stále aktuálnější, je jeho mnohem <i style="color:#D76F37;"><b>nižší cena</b></i>, než u paliv tradičních. S palivem E85 ušetříte na pohonných hmotách ročně tisíce korun. Více se o tomto
palivu dočtete <a class="hot_link" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'about')); ?>"  <?php echo '>'; ?>ZDE</a> .</p>

<h2>10 důvodů proč jezdit na E85</h2>
<div class="list">
    <ul>
        <li>Nižší cena až o 15 Kč na jednom litru</li>
        <li>Nízká pořizovací cena úpravy s rychlou návratností</li>
        <li>Zvýšení výkonu motoru</li>
        <li>Čistí motor, vstřikovací trysky a palivovou soustavu</li>
        <li>Nižší emise až o 75% (nesmrdí, nekouří)</li>
        <li>E85 je možné mísit s benzinem natural 95 nebo 98</li>
        <li>Šetrnější k pohonnému systému vozidla</li>
        <li>Není nutná přídavná nádrž</li>
        <li>Není nutný složitý a drahý zásah při přestavbě vozidla</li>
        <li>Není nutný zápis do technického průkazu</li>
    </ul>
</div>

<br />
<p>Pokud Vás výhody paliva E85 zaujaly, nepřehlédněte naší <a class="hot_link" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'services')); ?>"  <?php echo '>'; ?>akční nabídku </a>,
nebo pokud máte jakýkoliv dotaz, neváhejte nás <a class="hot_link" href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'contact')); ?>"  <?php echo '>'; ?>kontaktovat</a>.</p>

