<?php $this->title = "Mýty o ethanolu";
$this->headTitle($this->title); ?>

<p>Bohužel jak se občas stává, koluje mezi řidiči mnoho nepravdivých informací. My bychom je nazvali mýty a některé z těchto mýtů se týkají i biopaliv.</p>
<br><br />

<div class="myth">
<h2>Mýtus č.1</h2>
<p>Bioethanol poškozuje těsnění.</p>
<h3>PRAVDA</h3>
<p>Bioethanol těsnění nepoškozuje, naopak biopřísady v pohonných hmotách optimalizují vzplanutí a účinnost palivové směsi.</p>
</div>

<div class="decoration_lane_myth"></div>

<div class="myth">
<h2>Mýtus č.2</h2>
<p>Etahnol má neblahý vliv na palivové vedení a nádrž.</p>
<h3>PRAVDA</h3>
<p>Není to pravda, aby mohla nádrž prorezavět musí obsahovat vodu. Ethanol vodu váže a navíc nádrže z plastů nemohou prorezavět.</p>
</div>

<div class="decoration_lane_myth"></div>

<div class="myth">
<h2>Mýtus č.3</h2>
<p>Při používání ethanolu se nedá nastartovat při nízkých teplotách.</p>
<h3>PRAVDA</h3>
<p>Moderní řídící jednotka obsahuje funkci studený start, díky jíž lze startovat až do -30°C.</p>
</div>

