<?php $this->title = "Nabídka služeb";
$this->headTitle($this->title); ?>

<p>Zajišťujeme kompletní služby týkající se provozu automobilů využívajících palivo E85. Nabízíme vysoce kvalitní <a class="hot_link"
                                                                                                                     href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'kits')); ?>"  <?php echo '>'; ?>konverzní jednotky</a> starající se o
    správný vstřik paliva do válce, čímž je zajištěn bezpečný a bezproblémový provoz Vašeho automobilu.</p>
<br><br />

<h2>Co nabízíme</h2>
<p>Mimo samotného vybavení Vám také nabízíme kompletní <i style="color:#D76F37;"><b>doprovodné služby</b></i>, které jsou v rámci u nás pořízených jednotek zcela <i style="color:#D76F37;"><b>zdarma!</b></i>
    Při úpravě Vašeho automobilu namontujeme koverzní řídící jednotku, která upravuje vstřik paliva do válce. Naše jednotky mají automatický režim umožňující využívat poměru směsi E85 s benzínem v
    jakémkoliv poměru.</p>

<h3 style="text-align: left; text-decoration: underline;">Při objednání řídící jednotky zajistíme:</h3>

<div class="offer_list">
    <ul>
        <li>Dopravu zdarma</li>
        <li>Diagnostiku motoru zdarma</li>
        <li>Montáž zdarma</li>

    </ul>
    <br><br />
    <p>Co můžete udělat pro to, abyste mohli jezdit na E85? Stačí vyplnit objednávkový formulář a zbytek již zařídíme za Vás! Objednávejte <a class="hot_link"
                                                                                                                                              href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'kits')); ?>"  <?php echo '>'; ?>ZDE</a></p>

</div>
<h2></h2>
